### ISSUE TITLE
Why use a setuptools command?

### ISSUE THREAD

**Issue by wimglenn** [mschwager/0wned#1]
`pip install` will *execute* `setup.py`, and it has been that way since basically forever. You can just write Python code directly in the `setup.py` module, why bother to write a custom setuptools command?

**Comment by mschwager** [comment]
Good point!

Initially I thought I'd upload the package to PyPI and have people run `pip install 0wned`, but then I figured people would be weary of running that if I'm demo'ing arbitrary code execution :)

So I thought cloning the code, inspecting it to make sure it isn't doing anything _too_ malicious, then running `pip install` was a decent alternative.

P.S. I've since uploaded the package to PyPI anyway, so people are free to demo via that installation as well.

**Comment by mschwager** [comment]
Ahh, interesting! I was just testing out `pip install 0wned`, and the code execution doesn't work because it's a binary distribution like you were mentioning in #2! I wasn't aware of this functionality, I'll update the README :+1:

**Comment by mschwager** [comment]
I've updated the README. Feel free to re-open if you have other suggestions.

**Comment by wimglenn** [comment]
Perhaps the statement `You can hook almost any pip command by extending the correct setuptools module`, whilst correct, still unfairly points the finger at `setuptools`. They are working within the paradigm of [distutils](https://docs.python.org/3/library/distutils.html) and there are legitimate use-cases for code execution at install ("it's a feature"). The name of this repository makes it seem like you've discovered a vulnerability, but that's not really the case, it's just how installing source distributions works.
